### ISSUE TITLE
HTML is not defined when using IconRenderer in SSR

### ISSUE THREAD

**Issue by BeeMargarida** [svelteuidev/svelteui#256]
### What package has an issue

@svelteuidev/core

### A clear and concise description of what the bug is

When using `Tabs.Tab` with an icon, in SSR (default SvelteKit behaviour) it throws out the error below.

```
HTMLElement is not defined
ReferenceError: HTMLElement is not defined
    at IconRenderer.svelte:3:55
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1876:22)
    at Object.default (/@fs/Users/margarida/Documents/svelteui/packages/svelteui-core/package/components/Tabs/Tab/Tab.svelte:103:99)
    at eval (/@fs/Users/margarida/Documents/svelteui/packages/svelteui-core/package/components/Box/Box.svelte:118:41)
    at eval (/@fs/Users/margarida/Documents/svelteui/packages/svelteui-core/package/components/Box/Box.svelte:119:8)
    at Box.svelte:56:8
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1876:22)
    at eval (/@fs/Users/margarida/Documents/svelteui/packages/svelteui-core/package/components/Tabs/Tab/Tab.svelte:80:94)
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1876:22)
    at eval (/src/routes/+page.svelte:24:105)
```

### Steps To Reproduce

Example project in https://stackblitz.com/edit/sveltejs-kit-template-default-lvbvse?file=src/routes/+page.ts

Problematic code (in **SSR**): 

```
<script lang="ts">;
    import { Card, Container, Tabs } from "@svelteuidev/core";
    import { Value } from "radix-icons-svelte";

    const items = [1,2];
</script>

<Container>
    <Card>
        <Tabs>
            {#each items as _}
                <Tabs.Tab label="Settings" icon={Value}>Settings tab content</Tabs.Tab>
            {:else}
            
            {/each}
        </Tabs>
    </Card>
</Container>
```

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by BeeMargarida** [comment]
Fixed in 0.8.0
